spring:
  application:
    name: CentralniMetaregistar
  datasource:
    password: cmr1058
    driver-class-name: org.postgresql.Driver
    username: cmr
    url: jdbc:postgresql://localhost:5432/cmr
  jpa:
    hibernate:
      ddl-auto: none
logging:
  level:
    com:
      mycompany:
        myapp: INFO
server:
  port: 8080

